# docker-compose.yml 内容
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-app
    privileged: true  # 启用扩展权限
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: personal_seckill
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    container_name: phpmyadmin-container-app
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8079:80"
    networks:
      - my_network

  backend:
    image: swr.cn-north-4.myhuaweicloud.com/liuziyuan/backend:latest
    depends_on:
      - mysql
    pull_policy: always
    container_name: backend-app
    networks:
      - my_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container-app:3306/personal_seckill?serverTimezone=UTC&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "28080:28080"

  frontend:
    image: swr.cn-north-4.myhuaweicloud.com/liuziyuan/frontend:latest
    pull_policy: always
    container_name: frontend-app
    networks:
      - my_network
    ports:
      - "8080:80"


networks:
  my_network:

volumes:
  mysql:
