# docker-compose.yml 内容
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-app
    privileged: true  # 启用扩展权限
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: personal_seckill
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    container_name: phpmyadmin-container-app
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8079:80"
    networks:
      - my_network

  backend:
    image: swr.cn-north-4.myhuaweicloud.com/liuziyuan/backend:latest
    depends_on:
      - mysql
    pull_policy: always
    container_name: backend-app
    networks:
      - my_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container-app:3306/personal_seckill?serverTimezone=UTC&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "28080:28080"

  frontend:
    image: swr.cn-north-4.myhuaweicloud.com/liuziyuan/frontend:latest
    pull_policy: always
    container_name: frontend-app
    networks:
      - my_network
    ports:
      - "8080:80"

  redis:
    image: redis
    container_name: redis-container
    privileged: true  # 启用扩展权限
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - my_network
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    privileged: true  # 启用扩展权限
    networks:
      - my_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          memory: "512M"


networks:
  my_network:

volumes:
  mysql:
  redis-data:
  rabbitmq-data: